# syntax=docker/dockerfile:experimental
# Dockerfile used to run mix tests in the codebuild pipeline

FROM elixir:1.12-alpine as builder
RUN mkdir /build

COPY . /build/
WORKDIR /build

ARG MIX_ENV
ENV MIX_ENV=${MIX_ENV}

# Set up dependencies
RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get
RUN mix deps.compile

FROM elixir:1.12-alpine

# As of erts-12.x We need to manually add some libraries for the runtime to work.
RUN apk add --no-cache \
    bash \
    openssl \
    libgcc \
    libstdc++

RUN mkdir /testapp

ARG MIX_ENV
ENV MIX_ENV=${MIX_ENV}

COPY --from=builder /build/ /testapp
COPY --from=builder /root/.mix /root/.mix

WORKDIR /testapp

CMD mix test --no-deps-check
