version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
      args:
        MIX_ENV: test
    environment:
      - MIX_ENV=test
    command: mix test --no-deps-check
